"""QHub Python SDK - client library for the QHub prompt management API."""

from qhub.client import AsyncQHubClient, QHubClient
from qhub.errors import (
    APIError,
    AuthenticationError,
    ConflictError,
    ForbiddenError,
    NotFoundError,
    QHubError,
    RateLimitError,
    ValidationError,
)
from qhub.types import (
    Benchmark,
    ComplianceCheckResponse,
    ComplianceIssue,
    ConsultingMessage,
    ConsultingSession,
    CreateEvaluationRequest,
    CreateLogRequest,
    CreateMessageRequest,
    CreateSessionRequest,
    CreateTagRequest,
    CreateVersionRequest,
    DailyTrend,
    Evaluation,
    ExecutionLog,
    IndustryConfig,
    LintResult,
    Organization,
    Project,
    ProjectAnalytics,
    Prompt,
    PromptAnalytics,
    PromptVersion,
    SearchResponse,
    SearchResult,
    SemanticDiff,
    Tag,
    TextDiff,
    VersionAnalytics,
)

__version__ = "0.1.0"

__all__ = [
    # Clients
    "QHubClient",
    "AsyncQHubClient",
    # Errors
    "QHubError",
    "APIError",
    "AuthenticationError",
    "ConflictError",
    "ForbiddenError",
    "NotFoundError",
    "RateLimitError",
    "ValidationError",
    # Types
    "Benchmark",
    "ComplianceCheckResponse",
    "ComplianceIssue",
    "ConsultingMessage",
    "ConsultingSession",
    "CreateEvaluationRequest",
    "CreateLogRequest",
    "CreateMessageRequest",
    "CreateSessionRequest",
    "CreateTagRequest",
    "CreateVersionRequest",
    "DailyTrend",
    "Evaluation",
    "ExecutionLog",
    "IndustryConfig",
    "LintResult",
    "Organization",
    "Project",
    "ProjectAnalytics",
    "Prompt",
    "PromptAnalytics",
    "PromptVersion",
    "SearchResponse",
    "SearchResult",
    "SemanticDiff",
    "Tag",
    "TextDiff",
    "VersionAnalytics",
]
