// Originally generated by sqlc v1.30.0 from prompt_versions.sql.
// Manually edited: embedding-related queries removed.

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const archiveProductionVersion = `-- name: ArchiveProductionVersion :exec
UPDATE prompt_versions
SET status = 'archived'
WHERE prompt_id = $1 AND status = 'production'
`

func (q *Queries) ArchiveProductionVersion(ctx context.Context, promptID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, archiveProductionVersion, promptID)
	return err
}

const createPromptVersion = `-- name: CreatePromptVersion :one
INSERT INTO prompt_versions (prompt_id, version_number, status, content, variables, change_description, author_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, prompt_id, version_number, status, content, variables, change_description, semantic_diff, lint_result, author_id, published_at, created_at
`

type CreatePromptVersionParams struct {
	PromptID          uuid.UUID             `json:"prompt_id"`
	VersionNumber     int32                 `json:"version_number"`
	Status            string                `json:"status"`
	Content           json.RawMessage       `json:"content"`
	Variables         pqtype.NullRawMessage `json:"variables"`
	ChangeDescription sql.NullString        `json:"change_description"`
	AuthorID          uuid.UUID             `json:"author_id"`
}

func (q *Queries) CreatePromptVersion(ctx context.Context, arg CreatePromptVersionParams) (PromptVersion, error) {
	row := q.db.QueryRowContext(ctx, createPromptVersion,
		arg.PromptID,
		arg.VersionNumber,
		arg.Status,
		arg.Content,
		arg.Variables,
		arg.ChangeDescription,
		arg.AuthorID,
	)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.VersionNumber,
		&i.Status,
		&i.Content,
		&i.Variables,
		&i.ChangeDescription,
		&i.SemanticDiff,
		&i.LintResult,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPromptVersion = `-- name: GetLatestPromptVersion :one
SELECT id, prompt_id, version_number, status, content, variables, change_description, semantic_diff, lint_result, author_id, published_at, created_at FROM prompt_versions
WHERE prompt_id = $1
ORDER BY version_number DESC
LIMIT 1
`

func (q *Queries) GetLatestPromptVersion(ctx context.Context, promptID uuid.UUID) (PromptVersion, error) {
	row := q.db.QueryRowContext(ctx, getLatestPromptVersion, promptID)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.VersionNumber,
		&i.Status,
		&i.Content,
		&i.Variables,
		&i.ChangeDescription,
		&i.SemanticDiff,
		&i.LintResult,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProductionPromptVersion = `-- name: GetProductionPromptVersion :one
SELECT id, prompt_id, version_number, status, content, variables, change_description, semantic_diff, lint_result, author_id, published_at, created_at FROM prompt_versions
WHERE prompt_id = $1 AND status = 'production'
LIMIT 1
`

func (q *Queries) GetProductionPromptVersion(ctx context.Context, promptID uuid.UUID) (PromptVersion, error) {
	row := q.db.QueryRowContext(ctx, getProductionPromptVersion, promptID)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.VersionNumber,
		&i.Status,
		&i.Content,
		&i.Variables,
		&i.ChangeDescription,
		&i.SemanticDiff,
		&i.LintResult,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptVersion = `-- name: GetPromptVersion :one
SELECT id, prompt_id, version_number, status, content, variables, change_description, semantic_diff, lint_result, author_id, published_at, created_at FROM prompt_versions
WHERE prompt_id = $1 AND version_number = $2
`

type GetPromptVersionParams struct {
	PromptID      uuid.UUID `json:"prompt_id"`
	VersionNumber int32     `json:"version_number"`
}

func (q *Queries) GetPromptVersion(ctx context.Context, arg GetPromptVersionParams) (PromptVersion, error) {
	row := q.db.QueryRowContext(ctx, getPromptVersion, arg.PromptID, arg.VersionNumber)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.VersionNumber,
		&i.Status,
		&i.Content,
		&i.Variables,
		&i.ChangeDescription,
		&i.SemanticDiff,
		&i.LintResult,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptVersionByID = `-- name: GetPromptVersionByID :one
SELECT id, prompt_id, version_number, status, content, variables, change_description, semantic_diff, lint_result, author_id, published_at, created_at FROM prompt_versions WHERE id = $1
`

func (q *Queries) GetPromptVersionByID(ctx context.Context, id uuid.UUID) (PromptVersion, error) {
	row := q.db.QueryRowContext(ctx, getPromptVersionByID, id)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.VersionNumber,
		&i.Status,
		&i.Content,
		&i.Variables,
		&i.ChangeDescription,
		&i.SemanticDiff,
		&i.LintResult,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPromptVersions = `-- name: ListPromptVersions :many
SELECT id, prompt_id, version_number, status, content, variables, change_description, semantic_diff, lint_result, author_id, published_at, created_at FROM prompt_versions
WHERE prompt_id = $1
ORDER BY version_number DESC
`

func (q *Queries) ListPromptVersions(ctx context.Context, promptID uuid.UUID) ([]PromptVersion, error) {
	rows, err := q.db.QueryContext(ctx, listPromptVersions, promptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptVersion
	for rows.Next() {
		var i PromptVersion
		if err := rows.Scan(
			&i.ID,
			&i.PromptID,
			&i.VersionNumber,
			&i.Status,
			&i.Content,
			&i.Variables,
			&i.ChangeDescription,
			&i.SemanticDiff,
			&i.LintResult,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromptVersionLintResult = `-- name: UpdatePromptVersionLintResult :exec
UPDATE prompt_versions
SET lint_result = $2
WHERE id = $1
`

type UpdatePromptVersionLintResultParams struct {
	ID         uuid.UUID             `json:"id"`
	LintResult pqtype.NullRawMessage `json:"lint_result"`
}

func (q *Queries) UpdatePromptVersionLintResult(ctx context.Context, arg UpdatePromptVersionLintResultParams) error {
	_, err := q.db.ExecContext(ctx, updatePromptVersionLintResult, arg.ID, arg.LintResult)
	return err
}

const updatePromptVersionSemanticDiff = `-- name: UpdatePromptVersionSemanticDiff :exec
UPDATE prompt_versions
SET semantic_diff = $2
WHERE id = $1
`

type UpdatePromptVersionSemanticDiffParams struct {
	ID           uuid.UUID             `json:"id"`
	SemanticDiff pqtype.NullRawMessage `json:"semantic_diff"`
}

func (q *Queries) UpdatePromptVersionSemanticDiff(ctx context.Context, arg UpdatePromptVersionSemanticDiffParams) error {
	_, err := q.db.ExecContext(ctx, updatePromptVersionSemanticDiff, arg.ID, arg.SemanticDiff)
	return err
}

const updatePromptVersionStatus = `-- name: UpdatePromptVersionStatus :one
UPDATE prompt_versions
SET status = $1::varchar,
    published_at = CASE WHEN $1::varchar = 'production' THEN NOW() ELSE published_at END
WHERE id = $2
RETURNING id, prompt_id, version_number, status, content, variables, change_description, semantic_diff, lint_result, author_id, published_at, created_at
`

type UpdatePromptVersionStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdatePromptVersionStatus(ctx context.Context, arg UpdatePromptVersionStatusParams) (PromptVersion, error) {
	row := q.db.QueryRowContext(ctx, updatePromptVersionStatus, arg.Status, arg.ID)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.VersionNumber,
		&i.Status,
		&i.Content,
		&i.Variables,
		&i.ChangeDescription,
		&i.SemanticDiff,
		&i.LintResult,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}
