// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompts.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPrompt = `-- name: CreatePrompt :one
INSERT INTO prompts (project_id, name, slug, prompt_type, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, slug, prompt_type, description, latest_version, production_version, created_at, updated_at
`

type CreatePromptParams struct {
	ProjectID   uuid.UUID      `json:"project_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	PromptType  string         `json:"prompt_type"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreatePrompt(ctx context.Context, arg CreatePromptParams) (Prompt, error) {
	row := q.db.QueryRowContext(ctx, createPrompt,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.PromptType,
		arg.Description,
	)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.PromptType,
		&i.Description,
		&i.LatestVersion,
		&i.ProductionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrompt = `-- name: GetPrompt :one
SELECT id, project_id, name, slug, prompt_type, description, latest_version, production_version, created_at, updated_at FROM prompts WHERE id = $1
`

func (q *Queries) GetPrompt(ctx context.Context, id uuid.UUID) (Prompt, error) {
	row := q.db.QueryRowContext(ctx, getPrompt, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.PromptType,
		&i.Description,
		&i.LatestVersion,
		&i.ProductionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptByProjectAndSlug = `-- name: GetPromptByProjectAndSlug :one
SELECT id, project_id, name, slug, prompt_type, description, latest_version, production_version, created_at, updated_at FROM prompts
WHERE project_id = $1 AND slug = $2
`

type GetPromptByProjectAndSlugParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Slug      string    `json:"slug"`
}

func (q *Queries) GetPromptByProjectAndSlug(ctx context.Context, arg GetPromptByProjectAndSlugParams) (Prompt, error) {
	row := q.db.QueryRowContext(ctx, getPromptByProjectAndSlug, arg.ProjectID, arg.Slug)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.PromptType,
		&i.Description,
		&i.LatestVersion,
		&i.ProductionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPromptsByProject = `-- name: ListPromptsByProject :many
SELECT id, project_id, name, slug, prompt_type, description, latest_version, production_version, created_at, updated_at FROM prompts
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPromptsByProject(ctx context.Context, projectID uuid.UUID) ([]Prompt, error) {
	rows, err := q.db.QueryContext(ctx, listPromptsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prompt
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.PromptType,
			&i.Description,
			&i.LatestVersion,
			&i.ProductionVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrompt = `-- name: UpdatePrompt :one
UPDATE prompts
SET name = COALESCE($2, name),
    slug = COALESCE($3, slug),
    description = COALESCE($4, description),
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, name, slug, prompt_type, description, latest_version, production_version, created_at, updated_at
`

type UpdatePromptParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        sql.NullString `json:"name"`
	Slug        sql.NullString `json:"slug"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdatePrompt(ctx context.Context, arg UpdatePromptParams) (Prompt, error) {
	row := q.db.QueryRowContext(ctx, updatePrompt,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.PromptType,
		&i.Description,
		&i.LatestVersion,
		&i.ProductionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePromptLatestVersion = `-- name: UpdatePromptLatestVersion :one
UPDATE prompts
SET latest_version = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, name, slug, prompt_type, description, latest_version, production_version, created_at, updated_at
`

type UpdatePromptLatestVersionParams struct {
	ID            uuid.UUID `json:"id"`
	LatestVersion int32     `json:"latest_version"`
}

func (q *Queries) UpdatePromptLatestVersion(ctx context.Context, arg UpdatePromptLatestVersionParams) (Prompt, error) {
	row := q.db.QueryRowContext(ctx, updatePromptLatestVersion, arg.ID, arg.LatestVersion)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.PromptType,
		&i.Description,
		&i.LatestVersion,
		&i.ProductionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePromptProductionVersion = `-- name: UpdatePromptProductionVersion :one
UPDATE prompts
SET production_version = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, name, slug, prompt_type, description, latest_version, production_version, created_at, updated_at
`

type UpdatePromptProductionVersionParams struct {
	ID                uuid.UUID     `json:"id"`
	ProductionVersion sql.NullInt32 `json:"production_version"`
}

func (q *Queries) UpdatePromptProductionVersion(ctx context.Context, arg UpdatePromptProductionVersionParams) (Prompt, error) {
	row := q.db.QueryRowContext(ctx, updatePromptProductionVersion, arg.ID, arg.ProductionVersion)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.PromptType,
		&i.Description,
		&i.LatestVersion,
		&i.ProductionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
