// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addPromptTag = `-- name: AddPromptTag :exec
INSERT INTO prompt_tags (prompt_id, tag_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddPromptTagParams struct {
	PromptID uuid.UUID `json:"prompt_id"`
	TagID    uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddPromptTag(ctx context.Context, arg AddPromptTagParams) error {
	_, err := q.db.ExecContext(ctx, addPromptTag, arg.PromptID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (organization_id, name, color) VALUES ($1, $2, $3) RETURNING id, organization_id, name, color, created_at
`

type CreateTagParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	Color          string    `json:"color"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.OrganizationID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, organization_id, name, color, created_at FROM tags WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listPromptsByTag = `-- name: ListPromptsByTag :many
SELECT p.id, p.project_id, p.name, p.slug, p.prompt_type, p.description, p.latest_version, p.production_version, p.created_at, p.updated_at FROM prompts p JOIN prompt_tags pt ON p.id = pt.prompt_id WHERE pt.tag_id = $1
`

func (q *Queries) ListPromptsByTag(ctx context.Context, tagID uuid.UUID) ([]Prompt, error) {
	rows, err := q.db.QueryContext(ctx, listPromptsByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prompt
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.PromptType,
			&i.Description,
			&i.LatestVersion,
			&i.ProductionVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByOrg = `-- name: ListTagsByOrg :many
SELECT id, organization_id, name, color, created_at FROM tags WHERE organization_id = $1 ORDER BY name
`

func (q *Queries) ListTagsByOrg(ctx context.Context, organizationID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByPrompt = `-- name: ListTagsByPrompt :many
SELECT t.id, t.organization_id, t.name, t.color, t.created_at FROM tags t JOIN prompt_tags pt ON t.id = pt.tag_id WHERE pt.prompt_id = $1 ORDER BY t.name
`

func (q *Queries) ListTagsByPrompt(ctx context.Context, promptID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByPrompt, promptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePromptTag = `-- name: RemovePromptTag :exec
DELETE FROM prompt_tags WHERE prompt_id = $1 AND tag_id = $2
`

type RemovePromptTagParams struct {
	PromptID uuid.UUID `json:"prompt_id"`
	TagID    uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemovePromptTag(ctx context.Context, arg RemovePromptTagParams) error {
	_, err := q.db.ExecContext(ctx, removePromptTag, arg.PromptID, arg.TagID)
	return err
}
